app:
  baseUrl: https://platform-apps.andreskube.uk

backend:
  baseUrl: https://platform-apps.andreskube.uk
  database:
    client: pg
    connection:
      host: ${BACKSTAGE_DB_HOST}
      port: 5432
      user: backstage
      password: ${BACKSTAGE_DB_PASSWORD}

auth:
  environment: production
  providers:
    oidc:
      production:
        metadataUrl: http://keycloak.keycloak.svc.cluster.local:8080/realms/backstage/.well-known/openid-configuration
        clientId: backstage
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        callbackUrl: https://platform-apps.andreskube.uk/api/auth/oidc/handler/frame
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
